### ISSUE TITLE
Langage selected infleunces the language when click on link to luftdaten.info/home or luftdaten.info/sensorbuild

### ISSUE THREAD

**Issue by pjgueno** [opendata-stuttgart/devices.sensor.community#16]
Would it be possible to keep the language selected when someone click on the link to our main website?

**Comment by ricki-z** [comment]
@ohheyitsdave : We could add the language flag to the links to Luftdaten.info?

**Comment by ohheyitsdave** [comment]
do you mean on the homepage the links? We could easily to this in the po-Files. 
Look for home_url or around line 330. There we could adjust the links to the homepage and assembly guide.
