### ISSUE TITLE
Center map based on selected country 

### ISSUE THREAD

**Issue by DeeKey** [opendata-stuttgart/devices.sensor.community#2]
I hardware section of sensor registration there is a map. currently it is in some dummy position.
Would be nice to center it on the capital of the chosen country for more user convenience.

**Comment by ricki-z** [comment]
Link to map goes to world map. But there is a link now behind every sensor that opens a map view with the sensor in the center.

**Comment by Informatic** [comment]
I think whole address/location input needs some rework by someone comfortable with "frontend" development/JavaScript and UX. We've only added "Address lookup" button as this was a simple solution that wouldn't disturb anyone, in case they don't actually want to use it (sometimes address lookup returns rather random results)

**Comment by ricki-z** [comment]
@Informatic that is another "improvement". Deekey meant the map link on the sensor data page.
And that was changed, the first link to the whole world view and additional links for each sensor.

**Comment by ricki-z** [comment]
@DeeKey Is the actual solution okay?

**Comment by ricki-z** [comment]
@DeeKey can we close this?
The first map link can't be made language dependent. There are many countries with the same language.
But the link after the sensor ID should be okay for this.

**Comment by ricki-z** [comment]
@DeeKey let's talk about closing issues ;-)
Is this solved?

**Comment by DeeKey** [comment]
Yes :+1: >
