### ISSUE TITLE
permanent server overload?

### ISSUE THREAD

**Issue by michapr** [opendata-stuttgart/devices.sensor.community#56]
I get most time no data from server, only the empty map.
A self registration is not possible because of server timeout.

Any issues with server overload?

Thanks,
Michael

**Comment by haup** [comment]
I am also getting timeouts for my sensor probably since a couple of days. It seemed yesterday a bit better (api answered, but sensor data wasnt visible via webgui) , but this morning again no api response at all.

**Comment by ricki-z** [comment]
We are working on this. As the traffic has increased massively in some data centers the internal networks are sometimes overloaded.
For the moment it seems like we could solve this for the registration page, but not for our main database.
