### ISSUE TITLE
Sending wrong pressure data or unit?

### ISSUE THREAD

**Issue by tuxick** [opendata-stuttgart/devices.sensor.community#72]
I see my device send for my BME280:

`Pressure (hPa): 102824.97`

Which part is supposed to be correct? It should be (Pa) or 1028.25

**Comment by ricki-z** [comment]
Where do you see this? If it's a debug message then please ignore this. Pa is sent, even if there is shown hPa. We need to save space and may have "recycled" an existing text.

**Comment by tuxick** [comment]
Right, i saw that in debug after i saw home-assistant getting confused about getting strange values.

**Comment by ricki-z** [comment]
And how is home-assistant requesting this data? Via a call to data.sensor.community or by a call to the sensor local data.json?

**Comment by tuxick** [comment]
Both return pressure in Pa, so i just got confused by the debug output. Looks like a thing to adjust in HA then.
