### ISSUE TITLE
FR: devices.sensor.community: sensors: data: firmware version information (is missing)

### ISSUE THREAD

**Issue by ProBackup-nl** [opendata-stuttgart/devices.sensor.community#80]
Current devices.sensor.community user config sensor data nicely displays all sensors of the node.

Missing is the node its firmware release version that was used to publish this data.

As there was a sensor display strangely high PM values for a few weeks (starting June 28th), I was wondering which sensor was running which firmware version. Though I could not find the running firmware release at devices.sensors.community it's node.

This Feature Request is to include such information at https://github.com/opendata-stuttgart/devices.sensor.community/blob/develop/webapp/templates/my-sensor-data.html.

**Comment by ricki-z** [comment]
The firmware version isn't available for this server.
But you could use the page https://stats.sensor.community/scripts/firmware_versions.php to lookup the installed version for a known chipID.
Background: Some users decided to disable OTA updates. So with the knowledge of both the chipID and the database ID you could search for devices with old (and possibly vulnerable) firmware versions. That is one of the reason why we don't publish the chipID together with the database IDs.

**Comment by ProBackup-nl** [comment]
@ricki-z I would like to see historical versions of https://stats.sensor.community/scripts/firmware_versions.php to get an estimate at which point in time the sensor was running which firmware version. I kind of upgrade logging also helps.

I tried the Wayback machine, though it saved the [firmware_versions page only 4 times between September 24, 2020 and March 6, 2021](https://web.archive.org/web/*/https://stats.sensor.community/scripts/firmware_versions.php).

I also tried to figure out the beta version releases with https://firmware.sensor.community/airrohr/beta/ and https://firmware.sensor.community/airrohr/previous/. These folders don't contain 134-B1 / 134-B2 / 134-B3 and archive.org only saved Feb 25th and Aug 27th.

This all to figure out whether issue #919 was caused by a specific firmware version.
