### ISSUE TITLE
Temperature / humidity values are not displayed on map

### ISSUE THREAD

**Issue by tobias-tengler** [opendata-stuttgart/devices.sensor.community#89]
My P1 and P2 values are displayed on the map on sensor.community, but not the humidity and temperature. Looking at the dashboard the values are present though: 
![image](https://user-images.githubusercontent.com/45513122/159648572-b11e750e-7725-4f23-b9ed-3656588e576c.png)
I can also read them through the API: https://data.sensor.community/airrohr/v1/sensor/71307/

I had my sensor(s) marked as indoors, but changed it again for testing purposes, because I thought it could maybe prevent the indoor values from showing up on the map - does that make a difference?

EDIT: If this is the wrong repository to ask this question, please feel free to move the issue.

**Comment by pjgueno** [comment]
What Kind of sensors did you choose in your configuration interface on the Sensor ? Are they the same as in devices.Sensor.Community ?

Please send a Screenshot.

**Comment by pjgueno** [comment]
I think the scd30 is not set as RH/temp sensor in the map. Ist should be the reason.
As the co2 is not displayed on the map choose for example DHT22 in devices... It should work

**Comment by tobias-tengler** [comment]
These are the sensors I currently have configured: 
![image](https://user-images.githubusercontent.com/45513122/159657190-5355bb71-b1ae-4671-ae5a-6429d680ca81.png)

They match the actual hardware.

Thanks for the suggestion about switching to DHT22 - I'll try it out :)

**Comment by tobias-tengler** [comment]
After the switch to DHT22 it is indeed working as expected. Thanks for the help :)
