### ISSUE TITLE
Shows temperature on the map, but no data on devices.sensor.community

### ISSUE THREAD

**Issue by stsdc** [opendata-stuttgart/devices.sensor.community#92]
I'm confused that map shows temperature data, but I'm seeing "No current data are available for this sensor."  under _temperature/humidity/pressure sensor BME280_.

**Comment by pjgueno** [comment]
Did you select the same sensor type in both devices.sensor.community and the sensor itself?

**Comment by stsdc** [comment]
Can't check right now, but You're probably right.
